name: doc_generator
description: A sample command-line application
dependencies:
  unittest: any
//  docgen: '>=0.9.0 <0.10.0'
//  markdown:
//    git:
//      ref: emilysEdits
//      url: https://github.com/efortuna/dart-markdown
  
//  docgen:
//    svn: http://dart.googlecode.com/svn/trunk/dart/pkg/docgen/ 
//    url: https://code.google.com/p/dart/source/browse/trunk/dart/pkg/docgen/